apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
bases:
- ../../../lib/calico
- ../../../lib/coredns
- ../../../lib/serf
patchesStrategicMerge:
- patch-calico-node.yaml
- patch-serf-config.yaml
