---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: calico-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: calico-node
        env:
        - name: CALICO_ADVERTISE_CLUSTER_IPS
          value: 10.100.0.0/19
        - name: CALICO_IPV4POOL_IPIP
          value: Never
